version: '3.7'

services:
  db:
    image: postgres:16
    container_name: test_project_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  app:
    image: test_project_image
    build:
      context: .
    container_name: test_project_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["/test_project/docker/app.sh"]
    ports:
      - 7777:8000
